# Input Processing

## Setup
**'0_FolderSetup.s'**

 - Updated & renamed previous script (previous script was not being used) & added to 'HailMary.s'
 - Added 'UpdatedMasterNet' & 'UpdatedMasterNet\\GIS' folders to '0_InputProcessing' folder
 - Note: these changes were also made to '_CreateOutputFolders.s' & '_BlankFolderSetup' in the 'Scenarios\\_default' folder

**'1_InputSetup.s'**

 - Removed references in checks to 'CITY', 'COUNTY' fields in TAZ shapefile to account for removal of fields from TAZ shapefile

## SE Processing
**'1_DemographicsAnalysis.s'**

- Updated script to read 'ControlTotal_SE_AllCounties.csv'
    - Updated 'FILEI LOOKUPI[1]'' reference
    - Updated 'SE_ContTot' lookup function indices
- Updated control total lookup index calculation and added the following note:
 
    - ::: {.callout-note collapse="true"}
      ;look up county control totals
    
      ;  note: Weber Co control total uses the following CO_FIPS convention: 
    
      ;        57 = all county   (CO_FIPS) 
    
      ;      9057 = WFRC portion (90 prefix + CO_FIPS - 9=sub-county total, 0=UDOT  SubareaID) 
    
      ;      9157 = WFRC portion (91 prefix + CO_FIPS - 9=sub-county total, 1=UDOT  SubareaID) 
    
      BE_Index =    3 * 10000  +  @DemographicYear@ 
    
      WE_Index = 9157 * 10000  +  @DemographicYear@ 
    
      DA_Index =   11 * 10000  +  @DemographicYear@ 
    
      SL_Index =   35 * 10000  +  @DemographicYear@ 
    
      UT_Index =   49 * 10000  +  @DemographicYear@ 
      :::

## Network Processing

**'0_Update_TAZID_Distance.s'**

 - Updated script to export out true shape Link/Node shapefiles
 - Cleaned up script
    - Note: section to update DIRECTION and LINK_ID is commented out for now

**'1_NetProcessor.s'**

 - Removed references in checks to 'CITY', 'COUNTY' fields in TAZ shapefile to account for removal of fields from TAZ shapefile
 - Updated script to export out true shape Link/Node shapefiles
 - Fixed bug in CAV calculation:
 - From:
    - ::: {.callout-note collapse="true"}
      ;shift column indices by 1 to line up with lookup tables

      _CAV_Idx_Lower = _CAV_Idx_Lower + 1

      _CAV_Idx_Upper = _CAV_Idx_Upper + 1

      ;lookup the capacity factor for columns above & below input value

      if (LANES=2)

          _CapFac_CAV_Lo = CAV_CapFac_2Ln(_CAV_Idx_Lower, Cap1hr1ln)

          _CapFac_CAV_Hi = CAV_CapFac_2Ln(_CAV_Idx_Upper, Cap1hr1ln)

      elseif (LANES>=3)

          _CapFac_CAV_Lo = CAV_CapFac_3Ln(_CAV_Idx_Lower, Cap1hr1ln)

          _CapFac_CAV_Hi = CAV_CapFac_3Ln(_CAV_Idx_Upper, Cap1hr1ln)

      endif  ;LANES=2, LANES>=3
      :::

 - To:
    - ::: {.callout-note collapse="true"}
      ;lookup the capacity factor for columns above & below input value

      ; note: shift column indices by 1 to line up with lookup tables

      if (LANES=2)
  
          _CapFac_CAV_Lo = CAV_CapFac_2Ln(_CAV_Idx_Lower+1, Cap1hr1ln)

          _CapFac_CAV_Hi = CAV_CapFac_2Ln(_CAV_Idx_Upper+1, Cap1hr1ln)
  
      elseif (LANES>=3)
  
          _CapFac_CAV_Lo = CAV_CapFac_3Ln(_CAV_Idx_Lower+1, Cap1hr1ln)

          _CapFac_CAV_Hi = CAV_CapFac_3Ln(_CAV_Idx_Upper+1, Cap1hr1ln)
  
      endif  ;LANES=2, LANES>=3
      :::

**'3_TurnPenalty.s'**

 - Updated hard-coded turn penalty node numbers to new v8.3.2/v9.0 master network node numbering

**'4_Create_walk_xfer_access_links.s'**

 - Changed 'COUNTY' field in 'c_PNR_nodes.dbf' output to 'CO_FIPS' to account for removal of field from TAZ shapefile

## Trip Table

**'2_External_TripTables.'**

 - Replaced use of the 'EXTERNAL' field from TAZ shapefile with a reference to @external_zones@ field in 'General_Parameters.block' to account for removal of field from TAZ shapefile