---
title:  "Version 7.0.1 - What's New?"
date-modified: last-modified
author: "WFRC / MAG"
---

# Version 7.0.1
Changes in this version of the model affect usability and performance but do not affect model results.  Below is a description of the changes made in this model version.

## HailMary.s
With the release of 64 bit operating systems, such as in Windows 7, Cube software is installed in the program files x86 directory. This change broke the paths in the ‘HailMary.bat’ file to the Voyager executable. Rather than maintain two hailmary batch files (one for 32 bit operating systems and one for 64 bit systems), the model run launch point will now be done using a Cube script (HailMary.s). 

The 'HailMary.s' launch point offers a few advantages:

 - Running the 'ailMary.s' script should work regardless of where Cube software is installed.
 - Error handling for the entire model stream is handled in Voyager. Previously, the 'HailMary.bat' included error handling between model scripts while Voyager handled errors inside the scripts. 
A text file indicating the step of the model is still generated as the model runs. These files are now found in the root directory which helps the user see the progress of the model in one location. If the model were to crash, this file also informs the user the script where the crash occurred. 
The model run print file (*.PRN) is also found in the root directory and contains information from the entire model run. This has the advantage of not having to hunt for this file in the scripts folder to identify model fatal errors and other information. However, this file can be large, which is a drawback. The aggregate runtime reported in the Voyager run window also represents the entire model runtime and not simply the runtime for an individual script.
 - Viewing and modifying the 'HailMary.s' script is easier and uses the same logic/rules the user is familiar with in running Voyager scripts. The user does not need to be familiar with DOS to manipulate scripts in the model run.
 - The model now calls the '0GeneralParameters.block' and '1ControlCenter.block' files only once at the beginning of the model run. If a user still would like to run individual scripts, the user will simply need to uncomment the READ statements at the beginning of the individual script to read in the general and scenario specific parameters. When finished, the user will then re-comment out these READ statements.
