# Update For CUBE 6.4.5

Cube 6.4.5 required that all ZDATI input files be placed before any MATI input files.  This requirement was not in previous versions of Cube.  The scripts were update to comply with this new requirement so the travel model will run on Cube 6.4.5 without crashing.  That said, it is possible that future versions of Cube will address this issue.  

In addition, Cube 6.4.5 was improved to allow for faster assignment processing in.  According to Cube’s 6.4.5 release notes:

::: {.callout-note collapse="true"}
“New option F2 for PATHLOAD DEC keyword. Improves run time performance in path building.

New keyword MUTITHREAD to distribute Adjust phase across multiple processing cores. Includes sub keyword MEMORY, which is a Boolean option to set the temp files in memory or disk, when using MULTITHREAD. Only applies to COMBINE=EQUI.”
:::

The command 'DEC=F2' was put into the PATHLOAD control statement and 'MULTITHREAD=@CoresAvailable@, MEMORY=T' in the assignment 'block' files to improve model runtime.  These changes, however, resulted in only minor runtime improvements.  These improvements were left in the model scripts but were commented out so users of Cube prior to the 6.4.5 release can still use the model.  For those wishing to use this enhancement and have Cube 6.4.5, they will need to uncomment these items.

The following files were updated as part of the Cube 6.4.5 work:

 - Distribution
    - 1_Distribution.s
    - 4pd_mainbody_distribution.block
    - 3_SumToDistricts_GRAVITY.s
 - Mode Choice
    - 03_Skim_auto.s
    - 06_HBW_logsums.s
    - 07_HBW_dest_choice.s
    - 11_Mc_HBW_HBO.s,12_Mc_NHB_HBC.s
    - 14_AsnTran.s
    - 18_SumToDistricts_FinalTripTables.s
 - Final Assignment
    - 4pd_mainbody_managedlanes.block
    - 4pd_mainbody_managedlanes_SelectLink.block


