---
title:  "Version 4.3.0 - What's New?"
date-modified: last-modified
author: "WFRC / MAG"
---

## “What, When, and Why” of next likely improvements
WFRC and MAG are satisfied that we have a solid, state-of-the-practice modeling system with many elements of best practice and advanced practice.  We see our needs shifting away from continuing on toward the cutting edge of the industry, and focusing our efforts instead on validating and documenting the system, and utilizing the tools as they are to assist development of the Regional Transportation Plan, and support project development.  Thus significant model development will move to the back burner, but tools and process improvements that improve the utility of the models for applications will likely continue as needed. 

## Long Term
### HBW destination choice
We’ve been working with PB Consult to develop a Home-Based Work destination choice model.  We had hoped it could be implemented by summer 2005, but it’s schedule now is uncertain.

### UrbanSim
UrbanSim is being utilized for the Wasatch Choices 2040 visioning process.  Its performance during this effort will manifest whether it should be further utilized to aid the development of socioeconomic projections used in the RTP (due in 2006).  

### Home Interview Survey
There is continued debate about what exactly is needed in this arena.  The committee involved in this is wrestling with how to scope for this, and design a survey or several surveys that will get us the most valuable information available for the money.

### Replace *TRNBUILD* with *PUBLIC TRANSPORT*
The transit travel times and assignment utilize the Citilab’s TrnBuild module, which is a carry over from the Minutp platform.  Citilabs ceased development on TrnBuild after acquiring the Public Transport (PT) module from a European firm that specialized in transit route choice and graphical display of results.  As we learn more about PT, we will replace TrnBuild.  We are unsure as to how much this will improve our accuracy of modeling transit, but it will certainly allow us access to better graphics and different analytical methods, which alone should highlight opportunities for improve
