---
margin-header: Version 4.3.0 - What's New?
---

## Managed lanes (HOV, Toll lanes)
The Mode Choice model was modified to allow drivers to choose whether to use HOV or toll lanes.  The Logit structure historically has stopped after identifying drive alone, shared ride 2 person, and 3+ persons.  Now it dips further to assess who in each of these categories would be willing to pay a toll if available, and who would be motivated to use HOV lanes – and even form new car pools as a result of HOV lanes.  Once mode choice has identified these persons, these “managed lane trip tables” are assigned to specifically identified managed lane links on the highway network.  Thus when comparing build/no-build, the MC model can determine the new shared-ride or toll linked trips created by the managed lanes (i.e. how many vehicle trips were eliminated by the lanes, or revenue generated by the lanes).  Network assignment then shows the levels of demand and capture rate of HOV eligible vehicles at points along the system.  

There are several nuances that complicate the implementation of these features to be aware of (detailed elsewhere).  1) The existing HOV lane is relatively new and it will be difficult to assess its true usage until congestion again becomes significant.  Hence calibrating to today’s usage levels may be less important than assessing the lanes usage and capture rates under significant congestion and relative to experience in other cities.  2) This implementation tends toward what one might expect of barrier separated lanes more than the “easy on-easy off” painted lanes that we have now.  In other words, with painted separation, someone who uses the lane may not actually enter the lane until the point they first encounter slow downs – and they may exit once speeds are back to normal.  Here, trips tagged to use the lane at any point will enter the lane at their first opportunity, and exit at the last possible moment.  Thus the number of users is similar, but the length of use may be quite different.  “If you’re going to use it at all, then use it for as long as possible” is how this implementation works.  We expect that this is a more realistic definition when long segments of the adjoining general lanes are congested (as opposed to today where only short sections are congested).

## Distribution improvements
An unexpected phenomenon relating to friction factor curves was observed and corrected.  We tested adding one minute to terminal times and expected to see trip lengths reduce somewhat (the feedback loop logically would encourage shorter distance trips if the time to take those trips is greater).  However, trips actually went further.  The investigation revealed that friction factor curves needed updating and slightly different implementation.  

To make a long story short, 4.3 beta has newly calibrated friction factor curves, as well as different curves for different conditions (curves specific to free flow speeds as well as congested speeds).  Non-work purposes were also “doubly constrained”.  At the advice of peers and observation of results, these are now more singly constrained.  The combination of distribution improvements also resulted in a model that calibrates without the aid of link penalties that have traditionally been applied at geographic choke points.

## Draft demographic distribution of GOPB’s latest county forecasts
A draft distribution of GOPB’s latest county level forecasts was available in January (see discussion in 4.2 What’s new).  We discovered in March that MAG’s processing of the employment totals resulted in more jobs in Utah County than GOPB intended.  This has been corrected in a “March DRAFT”.  Again, these numbers have not been reviewed by cities, and they may never be, since it is possible we will utilize UrbanSim to allocate the GOPB forecasts for our Regional Transportation Plan.



