---
margin-header: Version 9.0.0 - What's New?
---

# Mode Choice

Updates to the Mode Choice portion of the model include drive access links, transit skims, and district summaries.

## Drive Access Links

The `04_Create_drive_access_links.s` script was modified to reference the new `ControlTotal_SE_AllCounties.csv` input file. The control total lookup index calculation was updated to account for Weber County indexing between two sub-areas. The `9057` prefix is for the UDOT Subarea and `9157` prefix for the WFRC Subarea.

## Transit Skims

The `05_Skim_Tran.s` script was modified to account for the new bus speeds inputs. <mark>???INCLUDE REFERENCE HERE TO INPUT DATA - BUS SPEEDS???</mark> The lookup index is based on updated Functional Class groups shown in @tbl-hway-count.

```{python}
#| label: tbl-hway-count
#| tbl-cap: Updated Functional Class Groups for Bus Speed
#| echo: False
from IPython.display import Markdown
from tabulate import tabulate
table = [['Collectors & Locals', '1, 4-10'],
         ['Minor Arterials'    , '3'      ],
         ['Principal Arterials', '2'      ],
         ['Expressways'        , '11-19'  ],
         ['Freeways & Ramps'   , '20-49'  ]]
Markdown(tabulate(
  table, 
  headers=["Functional Class","FT"],
  tablefmt="pipe", 
  colalign=("left",)*2
))
```

## District Summaries

The `18_SumToDistricts_FinalTripTables.s` script was modified to change `COUNTY` field references to `CO_FIPS` for county summaries due to removal of field from TAZ shapefile.
