---
title:  "Version 4.2.0 - What's New?"
date-modified: last-modified
author: "WFRC / MAG"
---

## What were 4.0 and 4.1, and why were they necessary?
UTA’s Commuter Rail project had a number of specific Mode Choice improvements identified by FTA as necessary for them to be comfortable with the forecasts.  Their requirements led to a complete overhaul of the MC model, which is now estimated on local data, better calibrated, considerably better treatment of walk/drive access to transit, better Home-based college representations, and peak/off-peak modeling.  While important to transit forecasting, this change has a relatively minor effect on roadway volumes.  The new MC model was used for New Starts submittals, and constituted 4.0.  Shortly thereafter, we separated BRT as a specific mode (BRT was simply “slower LRT” in 4.0, but is now a discrete choice with alternative specific constant equal to ½ that of LRT in 4.1).  This “4.1” was given to MAG to help them get going on their BYU-UVSC BRT study.

