---
margin-header: Version 4.2.0 - What's New?
---

## Features added between Aug 30 and Jan 21, 2005.

### Mode Choice bypass option cuts run times in half
Mode choice can now be bypassed for applications where a standard or fixed transit set is assumed across scenarios (typical of highway only analysis).  This feature cuts run times from about 5 hours down to 1.5-2.5 hours.  Ratios of mode choice are recorded during a full MC run, and then moved to an off-model directory for use with the bypass option. Switching to bypass mode will cause the model to use the ratios to obtain the MC results rather than full MC run.  This reproduces MC results almost exactly.  If you make a highway change that would change the trip distribution, the ratios respond accordingly (i.e. if you had 1000 trips before between I-J, and 100 were transit, and now your highway change creates 2000 trips, then 200 transit trips will now exist.)

### CityX and Shares reports improved
CityX is now working again, assigning by the long-trip/short-trip method, and is MUCH easier to use.  (FYI: CityX's main function is to identify which vehicles have at least one trip end in the city, and which ones are only passing through, by link).  Before, it required listing out by hand the zones that made up your city or study area - kind of a tough exercise.  Now, you just use a link attribute to define the area.  Make a polygon around the area, set "inside = 1", then reference the field in the script instructions, and in seconds you'll get a visual display of who's who on the roads in your study area.  The mode choice shares report also required listing P zone and A zone by hand.  Now you can easily use link attributes (by creating a polygon or using a district ID) to obtain mode choice shares for any imaginable production/attraction pairing.

### Path file recording for Select-Link analysis
Cube/Voyager now allows you to record the highway assignment process to a “path file”, which you can load in Cube, select any link, and get a display of where all the trips using that link came from.  The process is tricky and can result in files over 25 Gigabytes each!  Development around this feature is a work in progress, but can be utilized to certain levels now.  Call Mike if you’re interested.

### Transit trips can be assigned to highways for analysis
Transit trip tables can now be assigned to the highway network, showing hypothetically the roadway person-trips that would have occurred in the absence of transit.  An accompanying VMT report shows the VMT averted by transit.  The approach is simplistic and doesn’t account for all the issues, but should give “ball-park figures”.  It is also useful for obtaining a transit screenline. 

### College trip shares re-estimated and re-calibrated
Though FTA accepted the MC results from the 4.0 model, they remained skeptical of the high share of college trips using transit (2030 results at the U of U had almost 50% of all trips made by transit).  Our research since 4.2 was first released suggests that the on-board survey implied there were more college transit trips than other data suggest.  Distribution to some colleges was also refined.  LRT/BRT lines serving colleges will show fewer boardings at the colleges than earlier versions.

### Draft demographic distribution of GOPB’s latest county forecasts
Assumptions on where people and jobs will be located, and how many, are one of the most fundamental inputs in modeling.  This input has not been changed for over three years.  GOPB recently updated their county level estimates of 2030.  The estimate for Utah County is up by more than 100,000 residents, so we felt compelled to try to reflect what this would do to demand in that county.  Thus a new DRAFT allocation of GOPB forecasts is available with this model, but should be used cautiously (because it is still undergoing review for bugs, and has not been seen or approved by the cities like the previous forecasts have been).