---
margin-header: Version 3.2.0 - What's New?
---

## Highway Analysis Tools
### "HOV Usage"
An “HOV Usage” script was first produced as part of the Inter-Regional Corridors study several years ago.  Its purpose was to offer insight as to whether an HOV lane could be filled by a sufficient number of shared-ride trips within the peak hour that had motive to use the lane (time savings).  The logic in the script was updated, and the output was further stratified.  In addition, the managed-capacity of HOV lanes was better accounted for within distribution and assignment.

The script still does not offer any insight regarding how many new carpools might be formed as a direct result of an HOV proposal.  Rather, it focuses only on those trips that are shared-ride for some other reason, but are nonetheless eligible to use the HOV lane.  New carpoolers is an important element in determining if an HOV proposal can actually increase the person-trip through-put.

### “Isochronal travel times”
The model now includes a method to map the travel times from all zones to or from a “focus zone”.  For example, you can select a CBD zone and get a .dbf listing of the free-flow time, AM peak time, or PM peak time from all zones in the network to that zone.  In this case the AM time would be most relevant, and the free-flow time is a good benchmark of comparison.  You can change the focus zone to a suburban area and learn how long it takes “to get home” in the PM peak from the CBD, or from anywhere else you might happen to be in the region.

A comparison feature allows you to take the difference between two alternative scenarios and map the change in travel times from one to the other.  ArcView projects are predefined to make mapping simple.

