---
margin-header: Version 3.2.0 - What's New?
---

## District Analysis Tool
Version 3.2 created a new “district analysis” tool set for creating and mapping results.  Several project-specific district sets were defined (MVC, 114th South, South Davis), and a “Master District” spreadsheet was set up to store any district sets created for specific purposes.  We have not yet figured out a way to apply these tools directly to transit, but the affect of transit scenarios on the highways can be determined through these tools.

### “1HwyStats_Districts”
This tool quantifies the total VMT, VHT, delay, average speed, and lane miles that are occurring within each of the defined districts.  Values are stratified by freeways, arterials, and all roads combined.  The output is a .dbf record that can be easily mapped to a shape file of the districts.  A comparison utility allows the changes between two alternatives to be mapped for some very enlightening results of how a proposal can affect all locations in the region.

### “District2District”
This tool reduces the trip purpose matrices (HBW, etc.) and the mode choice matrices to “district flow matrices”.  The results can be exported to Excel for easy analysis of trip interchanges between districts.  Unique applications include “screenline districts”, where all zones on one side of a screenline are labled 1, and the others labeled 2.  The resulting 2x2 matrix reveals how many trips of each matrix type cross the screenline.  County to county flows are also defined here.

### “District2District_HwyChoice”
Similar to the CityX processor, this tool will assign trips between up to 4x4 district interactions to the highway network.  An example application might be “What share of the trips on I-15 in South Davis go between North Davis/Weber and SL County? How many to the CBD?  How many to South Davis itself?”  The results are pre-mapped to a .vpr file, and can be easily tabled as well.

## “Demographic Summaries”
This script aggregates up to 5 demographics files by a specified district definition.  Typically three would be compared:  The WFRC/MAG 2001 base year and 2030 forecast plotted along side the current run (2012, or a custom 2030, etc).  The results are summarized as both a table and a .dbf that can be joined to a district shape file with an accompanying ArcView project.  This is a powerful means of quickly computing pop/emp totals within the districts, and comparing the demographics of the current run against the WFRC/MAG 2001 observed and 2030 forecast demographics.



