---
title:  "Version 9.0.0 - What's New?"
date-modified: last-modified
author: "WFRC / MAG"
---

# General Parameters

## Zone Parameters

With the update to the TAZ inputs, the TAZ references were made in various locations.

### TAZ Range and Highway Node References

TAZ and highway node references were update with new zone numbers as shown in @tbl-taz-highway-renumber.

```{python}
| label: tbl-taz-highway-renumber
| tbl-cap: Renumbered Range and Highway TAZs
| echo: False
from IPython.display import Markdown
from tabulate import tabulate
table = [['Used Zones'            ,'UsedZones'    ,'3629'            ],
         ['Box Elder County Range','BoxElderRange','1-153'           ],
         ['Weber County Range'    ,'WeberRange'   ,'154-581'         ],
         ['Davis County Range'    ,'DavisRange'   ,'582-905'         ],
         ['Salt Lake County Range','SLRange'      ,'906-2216'        ],
         ['Utah County Range'     ,'UtahRange'    ,'2217-3546'       ],
         ['Dummy Zones'           ,'Dummyzones'   ,'3547-3600'       ],
         ['External Zones'        ,'Externalzones','3601-3629'       ],
         ['North Brigham City'    ,'NorthBC'      ,'3604,3605,3606'  ],
         ['Highway Nodes'         ,'HwyNodes'     ,'10000-99999'     ]]
Markdown(tabulate(
  table, 
  headers=['Range','Code','TAZ']))
```
The following ranges were removed: RegionRange, WFRCRange, MAGRange.

### Updated College and University Node References

College and university were updated with new zone numbers. See @tbl-college-renumber. Where noted, several colleges were effectively discontinued, meaning references to these schools are still in the code base, but enrollment was set to zero. See ????INPUTS DOC REF ???? for more detail.

```{python}
| label: tbl-college-renumber
| tbl-cap: Renumbered College and University Zones
| echo: False
from IPython.display import Markdown
from tabulate import tabulate
table = [[ 'Ensign College'                , 'Main'      , '95 N 300 W<br>Salt Lake City, UT 84101'           , 'Ensign'        , 1029 , 'Existing'    ],
         [ 'Westminster College'           , 'Main'      , '1840 S 1300 E<br>Salt Lake City, UT 84105'        , 'Westmin'       , 1263 , 'Existing'    ],
         [ 'University of Utah'            , 'Main'      , '201 Presidents Cir<br>Salt Lake City, UT 84112'   , 'UOFU_Main'     , 1051 , 'Existing'    ],
         [ 'University of Utah'            , 'Medical'   , '30 N 1900 E<br>Salt Lake City, UT 84132'          , 'UOFU_Med'      , 1007 , 'Discontinued'],
         [ 'Weber State University'        , 'Main'      , '3848 Harrison Blvd<br>Ogden, UT 84403'            , 'WSU_Main'      ,  437 , 'Existing'    ],
         [ 'Weber State University'        , 'Davis'     , '2750 University Park Blvd<br>Layton, UT, 84041'   , 'WSU_Davis'     ,  693 , 'Existing'    ],
         [ 'Weber State University'        , 'West'      , '5627 S 3500 W<br>Roy, UT, 84067'                  , 'WSU_West'      ,  521 , 'Discontinued'],
         [ 'Salt Lake<br>Community College', 'Main'      , '4600 S Redwood Rd<br>Taylorsville, UT 84123'      , 'SLCC_Main'     , 1580 , 'Existing'    ],
         [ 'Salt Lake<br>Community College', 'South City', '1575 S State Street<br>Salt Lake City, UT 84115'  , 'SLCC_SC'       , 1231 , 'Existing'    ],
         [ 'Salt Lake<br>Community College', 'Jordan'    , '3491 W 9000 S<br>West Jordan, UT 84088'           , 'SLCC_JD'       , 1776 , 'Existing'    ],
         [ 'Salt Lake<br>Community College', 'Meadbrook' , '218 W 3900 S<br>Salt Lake City, UT 84107'         , 'SLCC_Mead'     , 1491 , 'Discontinued'],
         [ 'Salt Lake<br>Community College', 'Miller'    , '9750 S 300 W<br>Sandy, UT 84070'                  , 'SLCC_ML'       , 1886 , 'Existing'    ],
         [ 'Salt Lake<br>Community College', 'Library'   , '231 E 400 S<br>Salt Lake City, UT  84111'         , 'SLCC_LB'       , 1085 , 'Discontinued'],
         [ 'Salt Lake<br>Community College', 'Highland'  , '3760 S Highland Drive<br>Salt Lake City, UT 84106', 'SLCC_HL'       , 1525 , 'Discontinued'],
         [ 'Salt Lake<br>Community College', 'Airport'   , '551 2200 W<br>Salt Lake City, UT 84116'           , 'SLCC_Airp'     ,  979 , 'Discontinued'],
         [ 'Salt Lake<br>Community College', 'Westpointe', '2150 W Dauntless Ave<br>Salt Lake City, UT 84116' , 'SLCC_West'     ,  959 , 'Discontinued'],
         [ 'Salt Lake<br>Community College', 'Herriman'  , '14200 S 4000 W<br>Herriman, UT'                   , 'SLCC_HM'       , 2031 , 'Discontinued'],
         [ 'Brigham Young University'      , 'Main'      , '1 N University Hill<br>Provo, UT 84602'           , 'BYU'           , 2939 , 'Existing'    ],
         [ 'Utah Valley University'        , 'Main'      , '800 West University Parkway<br>Orem, UT 84058'    , 'UVU_Main'      , 2848 , 'Existing'    ],
         [ 'Utah Valley University'        , 'Geneva'    , '951 S Geneva Rd<br>Orem, UT 84058'                , 'UVU_Geneva'    , 2882 , 'Discontinued'],
         [ 'Utah Valley University'        , 'Lehi'      , '2301 W. Ashton Blvd<br>Lehi, UT 84043'            , 'UVU_Lehi'      , 2606 , 'Existing'    ],
         [ 'Utah Valley University'        , 'Vineyard'  , 'Mill Rd<br>Vineyard, UT'                          , 'UVU_Vine'      , 2809 , 'Future'      ],
         [ 'Utah Valley University'        , 'Payson'    , 'Future Nebo Belt Rd<br>Payson, UT'                , 'UVU_Payson'    , 3336 , 'Future'      ]]

merged_rows = []
prev_row = [''] * len(table[0]) # initialize with empty prev_row
merge_cols=[0] # index of which columns to include in merging

for row in table:
    merged_row  = row.copy()
    for idx, c in enumerate(row):
        if idx in merge_cols:
            if row[idx]==prev_row[idx]:
                merged_row[idx]  = ''
    merged_rows.append(merged_row)
    prev_row = row

Markdown(tabulate(
  merged_rows, 
  headers=['College or University','Campus','Address','Code','TAZ','Status']))
```

### Updated Special Generator Node References

Special generators were updated with new zone numbers, as shown in @tbl-specgen-renumber.

```{python}
| label: tbl-specgen-renumber
| tbl-cap: Renumbered College and University Zones
| echo: False
from IPython.display import Markdown
from tabulate import tabulate
table = [[ 'Lagoon Amusement Park'               , 'Lagoon'      , 781 ],
         [ 'Salt Lake City International Airport', 'Aiport'      , 965 ],
         [ 'LDS Salt Lake Temple Square'         , 'TempleSquare', 1035],
         [ 'Salt Lake City Main Library'         , 'SLC_Library' , 1147]]

Markdown(tabulate(
  table, 
  headers=['Special Generator','Code','TAZ']))
```


## Special Trip Table Parameters

The income break points for Salt Lake City International Airport were updated as shown in @tbl-airport-income.

```{python}
| label: tbl-airport-income
| tbl-cap: Airport Income Levels
| echo: False
from IPython.display import Markdown
from tabulate import tabulate
table = [['Low'   ,'Income_Lo', '$45,000'],
         ['Medium','Income_Md', '$75,000'],
         ['High'  ,'Income_Hi','$125,000']]
Markdown(tabulate(
  table, 
  headers=['Category Break Point','Code','Income']))
```

## County Identification

Removed the county identification section section containing the following variables: CountyRange, CountyName1, CountyName2, CountyName3, CountyName4, CountyName5, CO_Name1, CO_Name2, CO_Name3, CO_Name4, CO_Name5.

## Air Quality Conformity Reports

Removed the air quality conformity section containing the following variables broken down by each county and 3 cities: RE_ID, WE_ID, DA_ID, SL_ID, UT_ID, BE_ID, OC_ID, SC_ID, PC_ID.

## Household Disaggregation Parameters

The updated regional median income was $74,946 from 2019 5-year ACS, in 2019 dollars. This represents average for just the Wasatch Front region.

## Distribution, Mode Choice, and Assignment Parameters

### Auto Occupancy

The vehicle occupancy rates were updated expanded to additional trips purposes. See @tbl-occupancy and @tbl-occupancy-3p. Variables were renamed where indicated. Auto occupancy parameters were updated based on 2012 Household Travel Survey (reprocessed). Values represent average persons per vehicle for just the Wasatch Front model space. External trips are average for IX + XI, all other parameters are averages for II trips.
 
```{python}
| label: tbl-occupancy
| tbl-cap: Average Auto-Occupancy Codes and Rates
| echo: False
from IPython.display import Markdown
from tabulate import tabulate
table = [['Home-Based Work'                , 'VehOcc_HBW'     , "VEH_OCCUPANCY_HBW"     , '1.10'],
         ['Home-Based Shopping'            , 'VehOcc_HBShp'   , "VEH_OCCUPANCY_HBSHP"   , '1.63'],
         ['Home-Based Other'               , 'VehOcc_HBOth'   , "VEH_OCCUPANCY_HBOTH"   , '1.68'],
         ['Home-Based School'              , 'VehOcc_HBSch'   , "VEH_OCCUPANCY_HBSCH"   , '1.76'],
         ['Home-Based College'             , 'VehOcc_HBC'     , "VEH_OCCUPANCY_HBC"     , '1.12'],
         ['Non-Home-Based Work'            , 'VehOcc_NHBW'    , "VEH_OCCUPANCY_NHBW"    , '1.21'],
         ['Non-Home-Based Non-Work'        , 'VehOcc_NHBNW'   , "VEH_OCCUPANCY_NHBNW"   , '1.76'],
         ['Recreation'                     , 'VehOcc_Rec'     , ""                      , '1.68'],
         ['Home-Based Other (sub-category)', 'VehOcc_HBO	'   , "VEH_OCCUPANCY_HBO"     , '1.67'],
         ['Non-Home-Based (sub-category)'  , 'VehOcc_NHB	'   , "VEH_OCCUPANCY_NHB"     , '1.54'],
         ['External Work'                  , 'VehOcc_ExtWrk'  , ""                      , '1.16'],
         ['External Home-Based Other'      , 'VehOcc_ExtHBO'  , ""                      , '1.82'],
         ['Non-Home-Based'                 , 'VehOcc_ExtNHB'  , ""                      , '1.73'],
         ['External Recreation'            , 'VehOcc_ExtRec'  , ""                      , '1.73']]
Markdown(tabulate(
  table, 
  headers=["Trip Purpose","Code","Previous Code","Updated Value"],
  floatfmt=".2f"))
```

```{python}
| label: tbl-occupancy-3p
| tbl-cap: Average Auto-Occupancy Codes and Rates for Vehicles with 3+ Persons
| echo: False
from IPython.display import Markdown
from tabulate import tabulate
table = [['Home-Based Work'                , 'VehOcc_3p_HBW'  , 'VEH_OCC_3P_HBW'        , '3.53'],
         ['Home-Based Shopping'            , 'VehOcc_3p_HBShp', ''                      , '3.49'],
         ['Home-Based Other'               , 'VehOcc_3p_HBOth', ''                      , '3.73'],
         ['Home-Based School'              , 'VehOcc_3p_HBSch', ''                      , '3.88'],
         ['Home-Based College'             , 'VehOcc_3p_HBC'  , 'VEH_OCC_3P_HBC'        , '3.24'],
         ['Non-Home-Based Work'            , 'VehOcc_3p_NHBW' , ''                      , '3.71'],
         ['Non-Home-Based Non-Work'        , 'VehOcc_3p_NHBNW', ''                      , '3.71'],
         ['Recreation'                     , 'VehOcc_3p_Rec'  , ''                      , '3.73'],
         ['Home-Based Other (sub-category)', 'VehOcc_3p_HBO'  , 'VEH_OCC_3P_HBO'        , '3.68'],
         ['Non-Home-Based (sub-category)'  , 'VehOcc_3p_NHB'  , 'VEH_OCC_3P_NHB'        , '3.71']]
Markdown(tabulate(
  table, 
  headers=["Trip Purpose","Code","Previous Code","Updated Value"]
))
```


### Value of Time

Value of time was updated for 2019 dollars, as shown in @tbl-vot.

```{python}
| label: tbl-vot
| tbl-cap: Value of Time
| echo: False
from IPython.display import Markdown
from tabulate import tabulate
table =  [['Auto Work Trips'                   ,'VOT_Auto_Wrk'   , 22],
          ['Auto Work Trips - Low Income'      ,'VOT_Auto_Wrk_Lo', 9 ],
          ['Auto Work Trips - High Income'     ,'VOT_Auto_Wrk_Hi', 24],
          ['Auto Personal Trips'               ,'VOT_Auto_Per'   , 17],
          ['Auto Personal Trips - Low Income'  ,'VOT_Auto_Per_Lo', 7 ],
          ['Auto Personal Trips - High Income' ,'VOT_Auto_Per_Hi', 19],
          ['Auto External Trips'               ,'VOT_Auto_Ext'   , 20],
          ['Light Trucks'                      ,'VOT_LT'         , 37],
          ['Medium Trucks'                     ,'VOT_MD'         , 50],
          ['Heavy Trucks'                      ,'VOT_HV'         , 63],
          ['Toll Trips'                        ,'VOT_Toll'       , 63],
          ['High-Occupancy Toll Trips'         ,'VOT_HOT_DA'     , 63]]
Markdown(tabulate(
  table, 
  headers=["Category","Code","Value of Time (???UNITS???)"]
))
```
### Auto Operating Costs

Auto operating cost (AOC) were updated based on 2019 fuel cost & economy and vehicle maintenance. See @tbl-aoc.

```{python}
| label: tbl-aoc
| tbl-cap: Auto Operating Costs
| echo: False
from IPython.display import Markdown
from tabulate import tabulate
table =  [['Personal Vehicle Auto'            ,'AOC_Auto', 21.7],
          ['Commercial Vehicle - Light Truck' ,'AOC_LT'  , 27.3],
          ['Commercial Vehicle - Medium Truck','AOC_MD'  , 55.5],
          ['Commercial Vehicle - Heavy Truck' ,'AOC_HV'  , 74.3]]
Markdown(tabulate(
  table, 
  headers=["Category","Code","Auto Operating Cost (???UNITS???)"]
))
```

### Toll and HOT Costs

Toll and HOT Costs were updated as shown in @tbl-toll-hot-costs. Toll costs reflect a toll of approximately $5.00 for a 10.25 mi trip (average work distance) or $3.00 for a 6.5 mi trip (average trip distance of all trips) in 2019 dollars. The toll costs apply to links with a functional type of 40. HOT costs reflect a toll of approximately $3.50 for a 10.25 mi trip (average work distance) or $2.20 for a 6.5 mi trip (average trip distance of all trips) in 2019 dollars. HOT costs are applicable to links with a functional type of 38.

```{python}
| label: tbl-toll-hot-costs
| tbl-cap: Toll and High-Occupancy Toll Costs
| echo: False
from IPython.display import Markdown
from tabulate import tabulate
table = [['Toll Peak Cost'                   ,'Cost_Toll_Pk', 48],
         ['Toll Off-Peak Cost'               ,'Cost_Toll_Ok', 48],
         ['High-Occupancy Toll Peak Cost'    ,'Cost_HOT_Pk' , 34],
         ['High-Occupancy Toll Off-Peak Cost','Cost_HOT_Ok' , 17]]
Markdown(tabulate(
  table, 
  headers=["Category","Code","Cost (cent/mile)"]
))
```
### Prefix for Transit Skims

All transit skim prefix global variable tokens were replaced with values in scripts. Transit skim prefix variables were removed from the General Parameters file.


