---
title:  "Version 8.3.1 - What's New?"
date-modified: last-modified
author: "WFRC / MAG"
---

# Miscellaneous Changes

A small bug was fixed in the '1_TripTable.s' script in the '2_ModelScripts\\0_InputProcessing\\d_TripTable' folder.  The control totals for the Salt Lake International Airport and Lagoon zones were being assigned to the other location's output.  This fix will cause a localized change to the volumes near the airport and Lagoon.

A small bug fix was made to the '1_NetProcessor.s' script in the '2_ModelScripts\\0_InputProcessing\\ c_NetworkProcessing' folder.  When socioeconomic data is loaded on to the TAZ centroids, home-based job employment had supplanted the construction job variable.  This fix only affects labeling of socioeconomic data on the highway network in Cube and does not affect any travel model results.

TIME fields on the network were edited to have four decimal places of precision instead of two (added to improve speed calculations).
Subfolder structure was removed for '0_DeleteTempFiles.s' script in '2_ModelScripts\\7_PostProcessing' folder and corresponding edits were made in the '_HailMary.s' batch script.  

'_HailMary.s' was updated to include more detail in the email functions.
The 'Compare2Assignments.s' script in the '2_ModelScripts\\7_PostProcessing\\2_Compare2Nets' folder was updated to include SEGID, correct field names for free flow speed, and add Area Type comparison. The associated DEFAULT.VPR file was also cleaned up.  A script to compare two master networks, 'Compare_MasterNet.s', was also added to the '2_ModelScripts\\7_PostProcessing\\2_Compare2Nets' folder.
